services:
  api01: &api
    container_name: api01
    hostname: api01
    image: rinha-backend-image
    environment:
      - COLLECTOR_URL=collector:4317
      - SERVICE_NAME=api
      - DB_HOSTNAME=db
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api
    container_name: api02
    hostname: api02
    environment:
      - COLLECTOR_URL=collector:4317
      - SERVICE_NAME=api
      - DB_HOSTNAME=db
      - PORT=3001
    ports:
      - "3001:3001"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    container_name: db
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./infra/structure.sql:/docker-entrypoint-initdb.d/script.sql
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

  otel-collector:
    container_name: otel-collector
    hostname: collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./infra/otel-collector.yml:/etc/otel-collector.yml
    ports:
      - 4317:4317

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    restart: always

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
