version: "3.5"

services:
  api01: &api
    container_name: api01
    hostname: api01
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    environment:
      - DB_HOSTNAME=db
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api
    container_name: api02
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - PORT=3001
    ports:
      - "3001:3001"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    container_name: db
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./infra/structure.sql:/docker-entrypoint-initdb.d/script.sql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
